# Generated by Django 3.2.20 on 2023-07-26 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessHoursOfStores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('dayOfweek', models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('1', 'Wednesday'), ('1', 'Thursday'), ('1', 'Friday'), ('1', 'Saturday'), ('1', 'Sunday')], max_length=10)),
                ('start_time_local', models.TimeField()),
                ('end_time_local', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PollDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('timestamp_utc', models.DateTimeField()),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.BigIntegerField()),
                ('uptime_last_hour', models.TimeField()),
                ('uptime_last_day', models.TimeField()),
                ('uptime_last_week', models.TimeField()),
                ('downtime_last_hour', models.TimeField()),
                ('downtime_last_day', models.TimeField()),
                ('downtime_last_week', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StoreTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.IntegerField()),
                ('timezone_str', models.CharField(max_length=50)),
            ],
        ),
    ]
