# Generated by Django 3.2.20 on 2023-07-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polldetails',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
