# Generated by Django 3.2.20 on 2023-07-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_alter_polldetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polldetails',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], max_length=10),
        ),
    ]
