# Generated by Django 3.2.20 on 2023-07-27 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_alter_polldetails_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesshoursofstores',
            old_name='dayOfweek',
            new_name='dayOfWeek',
        ),
    ]
