# Generated by Django 3.2.20 on 2023-07-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_rename_dayofweek_businesshoursofstores_dayofweek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesshoursofstores',
            name='dayOfWeek',
            field=models.CharField(choices=[('0', 'Monday'), ('1', 'Tuesday'), ('2', 'Wednesday'), ('3', 'Thursday'), ('4', 'Friday'), ('5', 'Saturday'), ('6', 'Sunday')], max_length=10),
        ),
    ]
