# Generated by Django 3.2.20 on 2023-07-28 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_alter_businesshoursofstores_dayofweek'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessHoursOfStores',
        ),
    ]
