# Generated by Django 3.2.20 on 2023-07-31 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_businesshoursofstores'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='csv_data',
            field=models.FileField(null=True, upload_to='report_csv/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='downtime_last_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='downtime_last_hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='downtime_last_week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='uptime_last_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='uptime_last_hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='report',
            name='uptime_last_week',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='CSV_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=10)),
                ('report_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.report')),
            ],
        ),
    ]
