# Generated by Django 3.2.20 on 2023-07-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20230731_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv_report',
            name='report_data',
        ),
        migrations.AddField(
            model_name='csv_report',
            name='csv_report',
            field=models.FileField(null=True, upload_to='report_csv/'),
        ),
    ]
