# Generated by Django 3.2.20 on 2023-07-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20230731_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='csv_data',
        ),
    ]
